services:
  accounts:
    image: "gloonch/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -eazybank

  loans:
    image: "gloonch/loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -eazybank

  cards:
    image: "gloonch/cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      -eazybank


networks:
  eazybank:
    driver: "bridge"
