build:
  version: "1.0"

accounts:
  #  message:"Welcome to EazyBank accounts related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "Ayshwary@eazybank.com"
  onCallSupport:
    - (555) 256-5455
    - (555) 523-7896
