build:
  version: "2.0"

accounts:
  #  message:"Welcome to EazyBank cards related QA APIs"
  contactDetails:
    name: "Jim Smith - QA Lead"
    email: "Jimmis@eazybank.com"
  onCallSupport:
    - (555) 256-5524
    - (555) 523-1342