build:
  version: "3.0"

accounts:
#  message:"Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1342
