build:
  version: "1.0"

accounts:
  #  message:"Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Reine Amini - Product Owner"
    email: "Amini@eazybank.com"
  onCallSupport:
    - (555) 256-5455
    - (555) 523-7896
