build:
  version: "3.0"

accounts:
#  message:"Welcome to EazyBank laons related local APIs"
  contactDetails:
    name: "Loana Muma - Developer"
    email: "Loana@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1342
