build:
  version: "2.0"

accounts:
  #  message:"Welcome to EazyBank loans related QA APIs"
  contactDetails:
    name: "Samira Fonteo - QA Lead"
    email: "Fonteo@eazybank.com"
  onCallSupport:
    - (555) 256-5524
    - (555) 523-1342