server:
  port: 8080
spring:
  datasource:
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "prod"


build:
  version: "3.0"

accounts:
#  message:"Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "John@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1342
